VM_PROVIDER = :virtualbox
PROVISION_TYPE = :shell
PROVISION_PATH = "scripts"
NETWORK_TYPE = "private_network"
DEFAULT_CPU = "1"
DEFAULT_RAM = "1024"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "server" do |server|
    server.vm.hostname = "apalumbiS"
    server.vm.network NETWORK_TYPE, ip: "192.168.56.110"

    server.vm.provider VM_PROVIDER do |v|
      v.cpus = DEFAULT_CPU.to_i
      v.memory = DEFAULT_RAM.to_i
    end

    server.vm.provision PROVISION_TYPE, path: "#{PROVISION_PATH}/apalumbiS_init.sh"
  end

  config.vm.define "server_worker" do |server_worker|
    server_worker.vm.hostname = "apalumbiSW"
    server_worker.vm.network NETWORK_TYPE, ip:"192.168.56.111"

    server_worker.vm.provider VM_PROVIDER do |v|
      v.cpus = DEFAULT_CPU.to_i
      v.memory = DEFAULT_RAM.to_i
    end

    server_worker.vm.provision PROVISION_TYPE, path: "#{PROVISION_PATH}/apalumbiSW_init.sh"
  end
end