Vagrant.configure("2") do |config|
  config.vm.box = "gutehall/ubuntu24-04"
  config.vm.box_version = "2025.02.20"

  nodes = [
    { hostname: "apalumbiS", ip: "192.168.56.110" },
    { hostname: "apalumbiSW", ip: "192.168.56.111" }
  ]

  nodes.each do |node|
    config.vm.define node[:hostname] do |vm| 
      vm.vm.hostname = node[:hostname]
      vm.vm.network "private_network", ip: node[:ip]

      vm.vm.provider :vmware_desktop do |v|
        v.vmx["numvcpus"] = "1"
        v.vmx["memsize"] = "1024"
      end

      vm.vm.provision "shell", path: "scripts/#{node[:hostname]}_init.sh"
    end
  end
end
